export function exportToCSV(data, filename) {
  const headers = Object.keys(data[0]);
  const csv = [
    headers.join(','),
    ...data.map(row => headers.map(h => row[h]).join(','))
  ].join('\n');

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  window.URL.revokeObjectURL(url);
}

export function exportToExcel(data, metadata, filename) {
  // Fallback ke CSV dengan format Excel-friendly jika library xlsx tidak tersedia
  const lines = [];
  
  // Header dengan informasi lengkap
  lines.push('LAPORAN DATA TIMBANG AYAM');
  lines.push('Smart Farm Layer 4.0');
  lines.push('');
  
  // Informasi Kandang
  lines.push('INFORMASI KANDANG');
  lines.push(`Kode Kandang,${metadata.kandangKode}`);
  lines.push(`Nama Kandang,${metadata.kandangNama}`);
  lines.push(`Penanggung Jawab,${metadata.penanggungJawab}`);
  lines.push(`Kontak,${metadata.kontak}`);
  if (metadata.kapasitas) {
    lines.push(`Kapasitas,${metadata.kapasitas} ekor`);
  }
  lines.push('');
  
  // Informasi Timbang
  lines.push('INFORMASI TIMBANG');
  lines.push(`Tanggal Export,${new Date().toLocaleDateString('id-ID')}`);
  
  // Cek tipe data
  if (metadata.umurMg) {
    // Single session data
    lines.push(`Umur Ayam,Minggu ${metadata.umurMg}`);
    lines.push(`Tanggal Timbang,${metadata.tanggal}`);
    lines.push(`Total Ekor Ditimbang,${metadata.totalEkor} ekor`);
    lines.push('');
    lines.push('HASIL ANALISA');
    lines.push(`Rata-rata Berat,${metadata.mean} gram`);
    lines.push(`Keseragaman (Uniformity),${metadata.uniformity}%`);
    lines.push(`Koefisien Variasi (CV),${metadata.cv}%`);
    lines.push(`Standar Deviasi,${metadata.stdDev} gram`);
    lines.push('');
    lines.push('DATA TIMBANG PER EKOR');
    lines.push('No,ID Ayam,Berat (gram),Waktu Input');
    
    data.forEach((row, index) => {
      lines.push(`${index + 1},${row.id_ayam},${row.berat},"${new Date(row.created_at).toLocaleString('id-ID')}"`);
    });
  } else {
    // Trend data
    lines.push(`Total Minggu,${metadata.totalMinggu}`);
    lines.push(`Total Ekor Keseluruhan,${metadata.totalEkor} ekor`);
    lines.push(`Rata-rata Keseluruhan,${metadata.rataRataKeseluruhan} gram`);
    lines.push('');
    lines.push('TREN PERTUMBUHAN PER MINGGU');
    lines.push('Minggu,Rata-rata Berat (gr),Total Ekor,Keseragaman (%),Tanggal Timbang');
    
    data.forEach((row) => {
      lines.push(`Minggu ${row.minggu},${row.rataRata},${row.totalEkor},${row.uniformity},"${row.tanggal}"`);
    });
  }
  
  // Footer
  lines.push('');
  lines.push(`Diekspor pada,"${new Date().toLocaleString('id-ID')}"`);
  lines.push('Generated by Smart Farm Layer 4.0 - shakadigital.com');
  
  // Buat file CSV yang Excel-friendly
  const csv = lines.join('\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.replace('.xlsx', '.csv');
  a.click();
  window.URL.revokeObjectURL(url);
}

export function exportToPDF(data, metadata, filename) {
  const isTrend = !metadata.umurMg;

  const html = isTrend ? `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { text-align: center; color: #10b981; margin-bottom: 5px; }
        h2 { text-align: center; color: #666; font-size: 14px; margin-top: 0; }
        .section { margin: 20px 0; }
        .section-title { background: #10b981; color: white; padding: 8px; font-weight: bold; }
        .info-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        .info-table td { padding: 5px; border-bottom: 1px solid #ddd; }
        .info-table td:first-child { font-weight: bold; width: 200px; }
        .data-table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 12px; }
        .data-table th { background: #10b981; color: white; padding: 8px; text-align: left; }
        .data-table td { padding: 6px; border-bottom: 1px solid #ddd; }
        .data-table tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        .stats-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin: 10px 0; }
        .stat-card { border: 2px solid #10b981; padding: 10px; border-radius: 5px; }
        .stat-label { font-size: 12px; color: #666; }
        .stat-value { font-size: 20px; font-weight: bold; color: #10b981; }
      </style>
    </head>
    <body>
      <h1>LAPORAN TREN PERTUMBUHAN AYAM</h1>
      <h2>Smart Farm Layer 4.0</h2>

      <div class="section">
        <div class="section-title">INFORMASI KANDANG</div>
        <table class="info-table">
          <tr><td>Kode Kandang</td><td>${metadata.kandangKode}</td></tr>
          <tr><td>Nama Kandang</td><td>${metadata.kandangNama}</td></tr>
          <tr><td>Penanggung Jawab</td><td>${metadata.penanggungJawab}</td></tr>
          <tr><td>Kontak</td><td>${metadata.kontak}</td></tr>
          ${metadata.kapasitas ? `<tr><td>Kapasitas</td><td>${metadata.kapasitas} ekor</td></tr>` : ''}
        </table>
      </div>

      <div class="section">
        <div class="section-title">RINGKASAN</div>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-label">Total Minggu</div>
            <div class="stat-value">${metadata.totalMinggu}</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">Total Ekor</div>
            <div class="stat-value">${metadata.totalEkor}</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">Rata-rata Keseluruhan</div>
            <div class="stat-value">${metadata.rataRataKeseluruhan} gr</div>
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">TREN PERTUMBUHAN PER MINGGU</div>
        <table class="data-table">
          <thead>
            <tr>
              <th>Minggu</th>
              <th>Rata-rata Berat (gr)</th>
              <th>Total Ekor</th>
              <th>Keseragaman (%)</th>
              <th>Tanggal Timbang</th>
            </tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>
                <td>Minggu ${row.minggu}</td>
                <td>${row.rataRata} gr</td>
                <td>${row.totalEkor} ekor</td>
                <td>${row.uniformity}%</td>
                <td>${row.tanggal || '-'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>

      <div class="footer">
        Diekspor pada: ${new Date().toLocaleString('id-ID')}<br>
        Smart Farm Layer 4.0 - Sistem Timbang Ayam
      </div>
    </body>
    </html>
  ` : `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { text-align: center; color: #10b981; margin-bottom: 5px; }
        h2 { text-align: center; color: #666; font-size: 14px; margin-top: 0; }
        .section { margin: 20px 0; }
        .section-title { background: #10b981; color: white; padding: 8px; font-weight: bold; }
        .info-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        .info-table td { padding: 5px; border-bottom: 1px solid #ddd; }
        .info-table td:first-child { font-weight: bold; width: 200px; }
        .data-table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 12px; }
        .data-table th { background: #10b981; color: white; padding: 8px; text-align: left; }
        .data-table td { padding: 6px; border-bottom: 1px solid #ddd; }
        .data-table tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; font-size: 12px; color: #666; }
        .stats-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 10px 0; }
        .stat-card { border: 2px solid #10b981; padding: 10px; border-radius: 5px; }
        .stat-label { font-size: 12px; color: #666; }
        .stat-value { font-size: 24px; font-weight: bold; color: #10b981; }
      </style>
    </head>
    <body>
      <h1>LAPORAN DATA TIMBANG AYAM</h1>
      <h2>Smart Farm Layer 4.0</h2>

      <div class="section">
        <div class="section-title">INFORMASI KANDANG</div>
        <table class="info-table">
          <tr><td>Kode Kandang</td><td>${metadata.kandangKode}</td></tr>
          <tr><td>Nama Kandang</td><td>${metadata.kandangNama}</td></tr>
          <tr><td>Penanggung Jawab</td><td>${metadata.penanggungJawab}</td></tr>
          <tr><td>Kontak</td><td>${metadata.kontak}</td></tr>
          ${metadata.kapasitas ? `<tr><td>Kapasitas</td><td>${metadata.kapasitas} ekor</td></tr>` : ''}
        </table>
      </div>

      <div class="section">
        <div class="section-title">INFORMASI TIMBANG</div>
        <table class="info-table">
          <tr><td>Umur Ayam</td><td>Minggu ${metadata.umurMg}</td></tr>
          <tr><td>Tanggal Timbang</td><td>${metadata.tanggal}</td></tr>
          <tr><td>Total Ekor Ditimbang</td><td>${metadata.totalEkor} ekor</td></tr>
        </table>
      </div>

      <div class="section">
        <div class="section-title">HASIL ANALISA</div>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-label">Rata-rata Berat</div>
            <div class="stat-value">${metadata.mean} gr</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">Keseragaman</div>
            <div class="stat-value">${metadata.uniformity}%</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">Koefisien Variasi (CV)</div>
            <div class="stat-value">${metadata.cv}%</div>
          </div>
          <div class="stat-card">
            <div class="stat-label">Standar Deviasi</div>
            <div class="stat-value">${metadata.stdDev} gr</div>
          </div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">DATA TIMBANG PER EKOR</div>
        <table class="data-table">
          <thead>
            <tr>
              <th>No</th>
              <th>ID Ayam</th>
              <th>Berat (gram)</th>
              <th>Waktu Input</th>
            </tr>
          </thead>
          <tbody>
            ${data.map((row, index) => `
              <tr>
                <td>${index + 1}</td>
                <td>${row.id_ayam}</td>
                <td>${row.berat}</td>
                <td>${new Date(row.created_at).toLocaleString('id-ID')}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </div>

      <div class="footer">
        Diekspor pada: ${new Date().toLocaleString('id-ID')}<br>
        Smart Farm Layer 4.0 - Sistem Timbang Ayam
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}

export function getDistribution(weights, binSize = 100) {
  if (weights.length === 0) return [];
  
  const min = Math.min(...weights);
  const max = Math.max(...weights);
  const bins = [];
  
  for (let i = Math.floor(min / binSize) * binSize; i <= max; i += binSize) {
    const count = weights.filter(w => w >= i && w < i + binSize).length;
    bins.push({
      range: `${i}-${i + binSize}`,
      count
    });
  }
  
  return bins;
}
